name = "ImageColorThresholderApp"
uuid = "e253f47c-99a5-4462-a47e-a31f992eca7c"
authors = ["rakeshksr <rakeshksr@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
